import math
a = int(input(""))
b = int(input(""))
c = int(input(""))
d = int(input(""))
e = int(input(""))
min1 = min(a, b, c, d, e)
max1 = max(a, b, c, d, e)
plus = int(a + b + c + d + e)
print("Найменше число")
print(min1)
print("Набільше число")
print(max1)
print("Сумма чисел")
print(int(plus))